<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Models\**" />
    <EmbeddedResource Remove="Models\**" />
    <None Remove="Models\**" />
    <None Remove="View\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="11.6.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Infrastructure.CrossCutting.Identity\Infrastructure.CrossCutting.Identity.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="View\" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="CommandHandlers\**" />
    <Compile Remove="Commands\**" />
    <Compile Remove="Events\**" />
    <Compile Remove="Notifications\**" />
    <Compile Remove="Validations\**" />
  </ItemGroup>
</Project>
